fix: fix security issues
epam/ai-dial-chat-themes pull request #8
Opened 2023-10-20 15:05 UTC by mikitabut

2023-10-31 17:13 UTC, nepalevov commented
/deploy-review

2023-10-31 17:35 UTC, nepalevov commented
/deploy-review

2023-10-31 17:55 UTC, nepalevov commented
/deploy-review

2023-10-31 19:13 UTC, nepalevov commented
/deploy-review

2023-11-02 13:01 UTC, nepalevov requested changes

2023-11-02 13:01 UTC, nepalevov commented on nginx/themes.conf.template
> +        valid_referers none blocked www.example.com example.com;
example.com? huh?

2023-11-02 13:01 UTC, nepalevov commented on nginx/nginx.conf
> +    limit_req_zone $binary_remote_addr zone=slimits:5m rate=100r/s;
not sure it's a good idea since `binary_remote_addr` in complex envs, e.g. kubernetes, will be the same for all requesters. Need more research there.

2023-11-14 14:34 UTC, mikitabut commented on nginx/themes.conf.template
> +        valid_referers none blocked www.example.com example.com;
Hello @nepalevov 
Could you please change this to real server names, because actually I don't know how to specify that

2023-11-14 14:34 UTC, mikitabut commented on nginx/nginx.conf
> +    limit_req_zone $binary_remote_addr zone=slimits:5m rate=100r/s;
Did you have a chance to check this?

2023-11-14 16:10 UTC, nepalevov approved these changes

2023-11-14 16:13 UTC, merged